language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
before_install:
- gem install bundler:2.1.4
- nvm install --lts
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure:
  app: <name of app you created on heroku> (Ex: powerful-cove-00403)
  run: rails db:migrate
