language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
before_install:
- gem install bundler:2.1.4
- nvm install --lts
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure:  secure: "BgQt8FYek7/2wL4TKv4RKzanofnYVW9lvFW4fNRQJi/DCBln4SiphRgEj7kIaVwGHB4n+LaOMt6crLDyzH+UXZtm1snaV7QS/j5DsspTSzuUrmZcNFHyl4K1xHEnWL7/wRmXbvHOkxlCq8tskU02VCMcR3hWbjoO0i+sg1OlfrRibXII3ulglG2Xh3WHD7B9NG3DWho7zSDdbk6kACzE+VvGtBnE0MQWP9gOy+b7VKHPUxLmkqdqByd1BIPJAKdpPwvUX0eu15Im0Vv47U4BBLnpfFv12qCfgdOIeHopDPZhfwSeWS2zyrsZt2GVYlQyewIExS7150HHqq6KOliAqKz9CNpaMAsn2aBCb9l4hFyAdruX/NSwKnetKy/GmRftG2KUfL1TETh7SkGTgVuxaoGCMkU2qCoOIRcLNp3PM65lXtJ5zpAiyA7Hpd8pDErK0dLiUhcT5+4wUPYIu95AEHmvomtYLQS9FG82bssTuffBuOZVFzzSFDBgzMUHn1AHb8wiR69Uem9TJQiAR4yvoAshyjB7PSzvh1M0Lyjg4VibTMAKg66a4DK8bYwfHk+VVhz2QXuXzSEU0A+Y9I9iI3en2KGELRBfv90gZhh5L7QbGyrEvxmr6Aj49TQBTdG8WXiJs9smMqLmDBy1W2gkltUOeuHaCqubZZah6d9SP4U="
  app: nameless-plains-48795
  run: rails db:migrate
